name: CI

on:
  push:
    branches:
      - 'exp/github-actions'

jobs:
  build:
    name: Build, Scan, and Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build
      - name: Scan the app with ESLint
        run: npm run lint
      - name: Run unit tests
        run: npm run test:cov
